### ISSUE TITLE
Compatibility with reactJS native router-dom?

### ISSUE THREAD

**Issue by rchowdhe** [bencompton/framework7-react-app-template#14]
Hello,

I want to know, Is it possible to use reactJS native routes component with this template?
Actually i want to define routes in such manner as defined here [Router implementation for React Authentication](https://gist.github.com/dabit3/36eb8f10a0f67b601402a2ef614a3075) but its throwing error and in call stack i found route object passed as null in base function.

So i want to confirm can i integrate routes inside this template like reactJS native manner or i need to stick with the way defined by F7 for routes?

**Comment by nolimits4web** [comment]
It must be used in F7-way
