### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by ammar-zaidi** [bencompton/framework7-react-app-template#18]
after clone react template when i run (npm start) they give  throw er; // Unhandled 'error' event
but previous version runing.i also checked the port is not in use

**Comment by nolimits4web** [comment]
Use F7 CLI http://framework7.io/cli/

**Comment by ammar-zaidi** [comment]
> Use F7 CLI http://framework7.io/cli/

i am not a admin user so cant install (npm install -g framework7-cli).please provide url if i can clone or download zip
