### ISSUE TITLE
how to detect the device type

### ISSUE THREAD

**Issue by anuragnagarkota** [bencompton/framework7-react-app-template#5]
Hello Ben

First of all congratulations for this wonderful integration with React.

Can we detect the device in this- like we do in framework 7 by the following command-
Framework7.prototype.device

**Comment by bencompton** [comment]
Your top-level Framework7App component has an instance of Framework7 that you can access when needed for things like that. There are a couple of ways to get access that are documented here: http://framework7.io/react/init-app.html.

**Comment by anuragnagarkota** [comment]
Hey Ben

I tried that but got the following error
'import' and 'export' may only appear at the top level (192:1) when I write the following code

export const App = () => {
let framework7;
 let currentRoute;

 export const getFramework7 = () => framework7;
  export const getCurrentRoute = () => currentRoute;
  .....

**Comment by bencompton** [comment]
It appears that your exports are within your app component. This technique is demonstrated in the kitchen sink as well if you would like to see a complete example: https://github.com/bencompton/framework7-react/blob/master/kitchen-sink/components/App.tsx.

**Comment by anuragnagarkota** [comment]
Thanks Ben 

It worked!!!
