### ISSUE TITLE
Pushstate not working for android

### ISSUE THREAD

**Issue by oktayla** [bencompton/framework7-react-app-template#7]
Pushstate  is good working on F7+Vue,
but it's not working on F7+React
![ekran resmi 2017-04-22 00 50 25](https://cloud.githubusercontent.com/assets/45117/25297325/a1958458-26f5-11e7-9231-7afecc317148.png)

Exit from App When i touched back button on navigationbar
please let me know how can I fix it

**Comment by bencompton** [comment]
How are you running it on Android? For example, I just cloned this repo and tested pushState in Chrome on my Android phone. I also added it to home screen in Chrome and tried it that way. In both cases, the back button worked as expected.

Incidentally, any Framework7 initialization parameter can simply be passed in as props to the Framework7App component. This is what mine looks like:

```javascript
<Framework7App themeType="ios" routes={routes} pushState={true} pushStateSeparator="">
```

This is the only change I made after cloning the repo. Perhaps you could try making another clone and test it with the code above? I wouldn't expect my syntax to necessarily work differently than yours, but you never know.

**Comment by oktayla** [comment]
That's good, i changed my code and it worked.
But when back to home, does not "onRouteChange" need trigger?
