### ISSUE TITLE
Optional Parameter in Routing

### ISSUE THREAD

**Issue by anuragnagarkota** [bencompton/framework7-react-app-template#8]
Hey Ben

How the optional parameter could be passed in routing-
I need something like the following-
  path: '/product/:param' (I need the param to be optional). I tried to put ? in the end of the parameter just like react router but it is not working. Please guide.

Thanks

**Comment by bencompton** [comment]
Hello. As far as I know, optional parameters are not supported. Framework7 React gets its routing functionality from its Framework7 Vue dependency, and Framework7 Vue's `findMatchingRoute` method does not appear to currently handle optional parameters: 

https://github.com/nolimits4web/Framework7-Vue/blob/master/src/utils/router.js#L147
